### ISSUE TITLE
Issue when unzipping oc tools

### ISSUE THREAD

**Issue by dimitraz** [austincunningham/change_oc#41] opened 2019-07-03 09:47 UTC
```sh
➜  ~ change_oc
======================== Check for OC Version Installed =============================
The folowing versions of oc are installed at /opt/openshift
Installed
oc

================================= Download OC =======================================
Do you wish to install an oc binary yes/no ? yes
What version of oc do you wish to install ? 
 - 3.7
 - 3.9
 - 3.10
 - 3.11
 - 4.1
4.1
==========                                                                          
Request finished writing to file
================================= Extract OC =======================================
download version:  4.1

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
child_process.js:669
    throw err;
    ^

Error: Command failed: tar --warning=no-unknown-keyword -C 4.1 -zxvf 4.1.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at fs.exists (/usr/lib/node_modules/change_oc/src/extract.js:23:7)
    at suppressedCallback (fs.js:199:5)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)

```

**Comment by austincunningham** [comment] 2019-07-11 06:57
Thanks I able to reproduce .

**Comment by austincunningham** [comment] 2019-07-11 07:05
Looks like the download url has changed 
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.1.0.tar.gz was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at mirror.openshift.com Port 443</address>
</body></html>
```

**Comment by austincunningham** [comment] 2019-07-11 07:35
fixed in https://github.com/austincunningham/change_oc/pull/42, new npm release .0.0.25

**Comment by austincunningham** [comment] 2019-07-11 07:47
may be other issues, need to do more testing

**Closed** 2019-07-11 20:43 UTC
